apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubebackup.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "kubebackup.name" . }}"
    chart: "{{ template "kubebackup.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  selector:
    matchLabels:
      app: "{{ template "kubebackup.name" . }}"
      release: {{ .Release.Name | quote }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "kubebackup.name" . }}"
        chart: "{{ template "kubebackup.chart" . }}"
        release: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      serviceAccountName: {{ template "kubebackup.name" . }}
      containers:
      - name: kubebackup
        image: {{ template "kubebackup.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: cron_schedule
          value: {{ .Values.cron_schedule | quote }}
        - name: BUCKET
          value: {{ .Values.bucket_name | quote }}
        - name: REGION
          value: {{ .Values.region | quote }}
        - name: access_key
          value: {{ .Values.access_key | quote }}
        - name: secret_key
          valueFrom:
            secretKeyRef:
              name: {{ template "kubebackup.name" . }}
              key: secret_key
        - name: folder
          value: {{ .Values.folder | quote }}
        - name: endpoint
          value: {{ .Values.endpoint | quote }}
        volumeMounts:
        - name: data
          mountPath: /mnt/backup
          {{- if .Values.persistence.subPath }}
          subPath: {{ .Values.persistence.subPath }}
          {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "kubebackup.name" .) }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end -}}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
