apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubebackup.fullname" . }}
  labels:
    app: "{{ template "kubebackup.fullname" . }}"
    chart: "{{ template "kubebackup.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  secret_key: {{ default "" .Values.secret_key | b64enc | quote }}
