---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-backup
  namespace: "kube-backup"
  labels:
    app: kube-backup
rules:
  - apiGroups:
    - ''
    resources:
    - ''
    verbs:
    - get
    - list
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-backup
  labels:
    app: kube-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-backup
subjects:
  - name: kube-backup
    namespace: "kube-backup"
    kind: ServiceAccount
