apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-kubebackup
    name: kubebackup
  spec:
    replicas: 1
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-kubebackup
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: deployment-kubebackup
      spec:
        containers:
        - env:
          - name: CRON_SCHEDULE
            value: '00 00 * * *'
          - name: REGION
            valueFrom:
              secretKeyRef:
                key: REGION
                name: s3creds
                optional: false
          - name: BUCKET
            valueFrom:
              secretKeyRef:
                key: BUCKET
                name: s3creds
                optional: false
          - name: KEY
            valueFrom:
              secretKeyRef:
                key: KEY
                name: s3creds
                optional: false
          - name: SECRET
            valueFrom:
              secretKeyRef:
                key: SECRET
                name: s3creds
                optional: false
          image: cube8021/kubebackup:latest
          imagePullPolicy: Always
          name: kubebackup
kind: List
