apiVersion: v1
name: kubebackup
version: 0.1.0
appVersion: 0.1.0
description: Kubernetes backup tool.
icon: file://../kubebackup-stack-220x234.png
keywords:
- kubebackup
- backup
home: https://github.com/mattmattox/kubebackup
sources:
- https://github.com/mattmattox/kubebackup
maintainers:
- name: Matthew Mattox
  email: matthew.mattox@rancher.com
engine: bash
